steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/e-analogy-384607/test-ci:$COMMIT_SHA', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/e-analogy-384607/test-ci:$COMMIT_SHA']
