steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/test-ci/My First Project:$COMMIT_SHA', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/test-ci/My First Project:$COMMIT_SHA']
